#pragma once

#define EMPTY_TASK 0
#define INIT_TASK 1
#define SEARCH_TASK 10
#define INSERT_TASK 11
#define REMOVE_TASK 12
#define RANGE_SEARCH_TASK 13
#define SERIALIZE_TASK 20
#define DESERIALIZE_TASK 21
