#pragma once

// generated by GPT 4o

#include "host/inc/extendable_buffer.hpp"
#include "parallel.ipp"

#include <algorithm>
#include <cassert>
#include <cmath>
#include <pstl/execution_defs.h>
#include <vector>


template <typename T>
class SparseTable
{
private:
    std::vector<ExtendableBuffer<T>> table;
    ExtendableBuffer<int> log;

public:
    template <typename U, typename ConvFunc>
    SparseTable(const std::vector<U>& data, ConvFunc&& conv);
    T query(int L, int R);
};

#if 0  // original code
template <typename T>
SparseTable<T>::SparseTable(const std::vector<T>& data)
{
    int n = data.size();
    int K = std::log2(n) + 1;
    table.resize(K, std::vector<T>(n)); // 次元を入れ替え
    log.resize(n + 1);

    // Precompute logs
    log[1] = 0;
    for (int i = 2; i <= n; i++)
        log[i] = log[i / 2] + 1;

    // Initialize table for the intervals with length 1
    for (int i = 0; i < n; i++)
        table[0][i] = data[i]; // 次元を入れ替え

    // Compute values from smaller to bigger intervals
    for (int j = 1; j < K; j++) 
        for (int i = 0; i + (1 << j) <= n; i++)
            table[j][i] = std::min(table[j - 1][i], table[j - 1][i + (1 << (j - 1))]); // 次元を入れ替え
}
#else
template <typename T>
template <typename U, typename ConvFunc>
SparseTable<T>::SparseTable(const std::vector<U>& data, ConvFunc&& conv)
{
    const size_t n = data.size();

    const int K = static_cast<int>(std::log2(n)) + 1;
    table.resize(K);
    for (int i = 0; i < K; i++)
        table[i].reserve(n);

    log.reserve(n + 1);

    ParallelManager parallel{0};
    parallel.run(1, n + 1, [&](size_t s, size_t e) {
        int logi = static_cast<int>(std::log2(s));
        size_t next = (size_t{1} << (logi + 1)) - 1;
        for (size_t i = s; i < e; i++) {
            log[i] = logi;
            if (i == next) {
                logi++;
                next = 2 * next + 1;
            }
        }
    });

    // Initialize table for the intervals with length 1
    parallel.run(0, n, [&](size_t s, size_t e) {
        for (size_t i = s; i < e; i++)
            table[0][i] = conv(data[i]);
    });

    // Compute values from smaller to bigger intervals
    for (int j = 1; j < K; j++) {
        size_t end = n - (1 << j) + 1;
        parallel.run(0, end, [&](size_t s, size_t e) {
            for (size_t i = s; i < e; i++)
                table[j][i] = std::min(table[j - 1][i], table[j - 1][i + (1 << (j - 1))]);  // 次元を入れ替え
        });
    }
}
#endif

template <typename T>
T SparseTable<T>::query(int L, int R)
{
    int j = log[R - L + 1];
    return std::min(table[j][L], table[j][R - (1 << j) + 1]);  // 次元を入れ替え
}
