#pragma once

// generated by GPT 4o

#include <vector>
#include <cmath>
#include <algorithm>

template <typename T>
class SparseTable
{
private:
    std::vector<std::vector<T>> table;
    std::vector<int> log;

public:
    SparseTable(const std::vector<T>& data);
    T query(int L, int R);
};

template <typename T>
SparseTable<T>::SparseTable(const std::vector<T>& data)
{
    int n = data.size();
    int K = std::log2(n) + 1;
    table.resize(K, std::vector<T>(n)); // 次元を入れ替え
    log.resize(n + 1);

    // Precompute logs
    log[1] = 0;
    for (int i = 2; i <= n; i++)
        log[i] = log[i / 2] + 1;

    // Initialize table for the intervals with length 1
    for (int i = 0; i < n; i++)
        table[0][i] = data[i]; // 次元を入れ替え

    // Compute values from smaller to bigger intervals
    for (int j = 1; j < K; j++) 
        for (int i = 0; i + (1 << j) <= n; i++)
            table[j][i] = std::min(table[j - 1][i], table[j - 1][i + (1 << (j - 1))]); // 次元を入れ替え
}

template <typename T>
T SparseTable<T>::query(int L, int R)
{
    int j = log[R - L + 1];
    return std::min(table[j][L], table[j][R - (1 << j) + 1]); // 次元を入れ替え
}
